securex:
  client_id: ''
  client_password: ''
  hostname: visibility.amp.cisco.com
orbital:
  client_id: ''
  client_password: ''
  hostname: orbital.amp.cisco.com
sna:
  hostname: ''
  user: ''
  password: ''
  hostgroup: ''
